"""changed type of bar_code

Revision ID: 353f2523ad46
Revises: b6864f8d9e98
Create Date: 2022-04-23 15:25:35.621248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353f2523ad46'
down_revision = 'b6864f8d9e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('purchases_buyer_id_fkey', 'purchases', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('purchases_buyer_id_fkey', 'purchases', 'users', ['buyer_id'], ['id'])
    # ### end Alembic commands ###
