"""changed type of bar_code

Revision ID: b34981d6ffb8
Revises: 353f2523ad46
Create Date: 2022-04-23 15:34:14.144104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34981d6ffb8'
down_revision = '353f2523ad46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'purchases', 'users', ['buyer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    # ### end Alembic commands ###
