"""removed primary key from bar_code, it needs to not be unique

Revision ID: d980e47ca489
Revises: e940e449eeec
Create Date: 2022-04-23 15:59:26.284491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd980e47ca489'
down_revision = 'e940e449eeec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('transact_id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'transact_id')
    # ### end Alembic commands ###
